

spring:
  datasource:
    #        url: jdbc:mysql://localhost:3306/board
    #        username:
    #        password:
    #        driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true